version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
            - ./bootstrap/cache:/var/www/bootstrap/cache
        networks:
            - laravel

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx-server
        ports:
            - "8080:80"  # Expose on 0.0.0.0:8080
        depends_on:
            - app
        volumes:
            - .:/var/www
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
